### ISSUE TITLE
Create globally scoped css variables for the colors to reduce copy-pasting

### ISSUE THREAD

**Issue by JackBlake-zkq** [DSSD-Madison/couillard#17]
- See  [the mdn docs on css variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)

**Comment by residualentropy** [comment]
You didn't mention anything during the meeting, but did you get these?

**Comment by JackBlake-zkq** [comment]
Reduced the scope of this to just the css variables

**Comment by JackBlake-zkq** [comment]
Looks like someone did this at some point
