### ISSUE TITLE
Select a panel, have graph show only it, and show more info

### ISSUE THREAD

**Issue by Ka0nNeutral** [DSSD-Madison/couillard#24]
- [x] Allow you to select a certain array to focus on, and then have the graph and totals only be for that panel
- [x] Display image and description for selected array by using image url and description from array Firestore document

**Comment by JackBlake-zkq** [comment]
Add some placeholders to db (manually through firebase console) if #25 not done

**Comment by JackBlake-zkq** [comment]
Updated based on progress from #34
