### ISSUE TITLE
Setup Admin Spreadsheet to manage array documents

### ISSUE THREAD

**Issue by K40N** [DSSD-Madison/couillard#25]
Setup [Admin Google Sheet](https://docs.google.com/spreadsheets/d/1S9nvMsymOAseaOQ_cnDN_oBePvDAuavbSKx_wkPa8Bk/edit) so that:

- [x] Format to collect necessary fields to create/update array documents, and force updates of all historical data on an array
- [x] On the click of an "Update Arrays" button, a Google Apps Script function should run, and use [this library](https://github.com/grahamearley/FirestoreGoogleAppsScript) to:
  - [x] Sync array documents with spreadsheet (add new ones, update existing ones)
  - [x] Set the `needs_update` field to true for arrays with that box checked

**Comment by residualentropy** [comment]
We also need to add the frobenius/aurora dashboard URLs in order to link to them.

**Comment by JackBlake-zkq** [comment]
Use this Apps Script Lib: https://github.com/grahamearley/FirestoreGoogleAppsScript

**Comment by JackBlake-zkq** [comment]
See updated [README](../blob/main/README.md)

**Comment by JackBlake-zkq** [comment]
Going to split this into 2 issues: this one for the ss, one for the updated action

**Comment by JackBlake-zkq** [comment]
This is done (external apps script code) 👍
