### ISSUE TITLE
Make work on mobile

### ISSUE THREAD

**Issue by K40N** [DSSD-Madison/couillard#29]
- [x] List the different stats (CO2, $, kWh) vertically not horizontally
- [x] Just hide the graph section on mobile since it won't be very usable anyway
- [x] might be something messed up with array selector button to fix
- [x] make sure description and image stack instead of side by side

**Comment by residualentropy** [comment]
I'm going to hold off working on this since I don't want to have to deal with merge conflicts when we do #22 and #23 and #24. It's not a *major* priority anyway.

**Comment by K40N** [comment]
Now that the aforementioned PRs are complete, either I'd like to work on this or you guys can. I totally agree that it isn't a major priority, but since I'm done with the animations (hopefully) I believe I have the capacity to carry out.

**Comment by K40N** [comment]
Since it's so close to the end of the semester anyway I think it might be wise to drop this. @JackBlake-zkq

**Comment by JackBlake-zkq** [comment]
Good point, let's see where we are at on Sunday and decide then

**Comment by JackBlake-zkq** [comment]
Maybe will do this next sem 👍

**Comment by K40N** [comment]
Apparently we are working on this. Reopened.

**Comment by JackBlake-zkq** [comment]
Yeah I think this would be good. I'm thinking maybe we just hide the graph completely on mobile, since it wouldn't be very usable anyway. Then we would just need to make the totals fit and the image/description wrap around

**Comment by K40N** [comment]
Makes sense to me.

**Comment by JackBlake-zkq** [comment]
Addressed by 72f4c5ecf46667eb8b012acbac45e65f5a26cd64
