### ISSUE TITLE
Improve loading with animations/transitions

### ISSUE THREAD

**Issue by JackBlake-zkq** [DSSD-Madison/couillard#30]
Current loading dialog is very static, and things change suddenly once the data loads in. 

- change the loading dialog to be an animate spinner (maybe blur the rest of the page while loading too)
- use of [svelte transitions](https://svelte.dev/docs/svelte-transition) to make changes look less abrupt

**Comment by K40N** [comment]
Will work on this over the coming week (and maybe a bit after thanksgiving break too if it takes more time to clean everything up).

**Comment by K40N** [comment]
Created branch `loading-animations-etc`. I have a physics midterm and a Japanese assignment to do tomorrow, but I should still have some time to start this after that. I did read up about transitions in Svelte (thanks for linking to the docs). That's all for now :)
