### ISSUE TITLE
Image on bottom + Hint

### ISSUE THREAD

**Issue by traitboundnotsatisfied** [DSSD-Madison/couillard#38]
See the end of #36 for context. I think it would look nicer and more consistent if we put the image below the graph (like CSF said) but then we need a little hint of some sort telling them it's there.

The hint should be something like a small dialog at the bottom, and you should be able to click it to scroll down, and it should only be visible if you aren't scrolled down at all.

**Comment by K40N** [comment]
Implemented, creating PR now.
