### ISSUE TITLE
System to add untracked data to totals - Frontend

### ISSUE THREAD

**Issue by JackBlake-zkq** [DSSD-Madison/couillard#52]
CSF wants to add in some old data from before they started tracking with Fronius/Aurora to the totals. To allow this, we should do the following on the frontend:
- [x] add `old_data` field from document onto totals store
- [x] modify language in totals section to reflect change
  - Change the "Since we started tracking"
  - change the "many of our arrays have been operational for much longer than the data reflects..." to something like "totals are calculated from a combination of totals form the power company, and newer real-time tracking systems"
- [x] maybe add some text near the graph explaining that it only includes newer data

**Comment by K40N** [comment]
Are the they adding just the totals over the pre-us-tracking period or do we actually have the data too?

**Comment by JackBlake-zkq** [comment]
It is data from before they had the aurora/fronius things set up e.g. for the high school aurora old has data back to sept 2023, but they know based on what the power company told them how much energy they generated before sept. 2023

**Comment by K40N** [comment]
Sounds good, I'll start working on this today.

**Comment by JackBlake-zkq** [comment]
@K40N Can you throw in a PR for this? I see your stuff is pushed

**Comment by K40N** [comment]
Sorry I didn't see this earlier, thanks for resolving! :)
