### ISSUE TITLE
Spit Graph component

### ISSUE THREAD

**Issue by JackBlake-zkq** [DSSD-Madison/couillard#53]
Graph component is pretty huge and spans multiple sections of the page

We should split it into at least two components

**Comment by K40N** [comment]
I should be able to work on this over the next couple of days (once I finish CS 300 P01 at least....)

**Comment by K40N** [comment]
Ok I'm busy this week but will try to get it in Wednesday or over the weekend if I cant.

**Comment by JackBlake-zkq** [comment]
No rush, this one isn't urgent

**Comment by JackBlake-zkq** [comment]
@K40N Going to close this if you aren't planning on working on this soon

**Comment by K40N** [comment]
Sorry, I haven't checked my github for quite a while. But yeah since this didn't seem like a big deal and I've been doing other stuff hopefully it isn't problematic.
